name: Ejecutar script al agregar archivo

on:
  push:
    paths:
      - solicitudes/**  # Monitorea cambios en la carpeta 'solicitudes'

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Cambia la versi칩n si necesitas otra

      # 3. Ejecutar el script de Python
      - name: Ejecutar el script
        run: |
          python a침adeAlCambio.py
      # 4. Commit & Push
      - name: Hacer commit de los cambios
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Actualizar datos autom치ticamente' || echo "No hay cambios para hacer commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Usa el token para el push
