name: Actualizar datos cada 2 horas

on:
  schedule:
    - cron: '0 */2 * * *'  # Esto se ejecuta cada 2 horas
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo

jobs:
  update-data:
    runs-on: ubuntu-latest  # Utiliza un entorno Ubuntu en GitHub Actions

    steps:
      - name: Verificar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Especifica la versión de Python que quieres usar

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tienes dependencias en un archivo requirements.txt

      - name: Ejecutar script Python
        run: |
          python pruebaWorkflow.py  # Especifica la ruta a tu script Python

      - name: Hacer commit de los cambios (si los hay)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Actualizar datos automáticamente' || echo "No hay cambios para hacer commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token para el push
